# Generated by Django 3.1.2 on 2020-11-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0002_auto_20201102_0632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={},
        ),
        migrations.AlterModelOptions(
            name='neighborhood',
            options={},
        ),
        migrations.RemoveField(
            model_name='business',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='technologies',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
